export type DbEntry = {
  url: string;
  label?: string;
};

export function labelForDb(url: string): string {
  try {
    const u = new URL(url);
    return u.hostname.replace(/\.firebaseio\.com$|\.firebasedatabase\.app$/, "");
  } catch {
    return url;
  }
}

export const DEFAULT_DATABASE_URLS: string[] = [
  "https://aditya-9f66b-default-rtdb.firebaseio.com",
  "https://admin-panel-b2935-default-rtdb.firebaseio.com",
  "https://admin-panel-bfcdc-default-rtdb.firebaseio.com",
  "https://admin-panel-clinet-default-rtdb.firebaseio.com",
  "https://admon-aeba0-default-rtdb.firebaseio.com",
  "https://arahul-564dd-default-rtdb.firebaseio.com",
  "https://aug1-ea7c9-default-rtdb.firebaseio.com",
  "https://axis-bank-bf055-default-rtdb.firebaseio.com",
  "https://beeeddi-cc0e1-default-rtdb.firebaseio.com",
  "https://bhai-138a8-default-rtdb.firebaseio.com",
  "https://bmw1-bdc10-default-rtdb.firebaseio.com",
  "https://brahul-53f8b-default-rtdb.firebaseio.com",
  "https://callmebitchfumckyou-default-rtdb.firebaseio.com",
  "https://chfjfj-c2857-default-rtdb.firebaseio.com",
  "https://crahul-abcb4-default-rtdb.firebaseio.com",
  "https://cs2xc-3951e-default-rtdb.firebaseio.com",
  "https://customer03support-default-rtdb.firebaseio.com",
  "https://dipanshu-bf4d2-default-rtdb.firebaseio.com",
  "https://expert-5e1a0-default-rtdb.firebaseio.com",
  "https://fir-new-fe8b8-default-rtdb.firebaseio.com",
  "https://ghostx-panel-default-rtdb.firebaseio.com",
  "https://haab-b3370-default-rtdb.firebaseio.com",
  "https://hacker-panel-dcc53-default-rtdb.firebaseio.com",
  "https://hghg-6f0a8-default-rtdb.asia-southeast1.firebasedatabase.app",
  "https://hospital-new-11-default-rtdb.firebaseio.com",
  "https://human-34-kumar-default-rtdb.firebaseio.com",
  "https://i-am-subhu-default-rtdb.firebaseio.com",
  "https://khushibook-4685a-default-rtdb.firebaseio.com",
  "https://kishm-1d858-default-rtdb.firebaseio.com",
  "https://koya-7acd9-default-rtdb.firebaseio.com",
  "https://momo-fae14-default-rtdb.firebaseio.com",
  "https://muskhshj-default-rtdb.firebaseio.com",
  "https://navin-9fb56-default-rtdb.firebaseio.com",
  "https://pint-f465b-default-rtdb.firebaseio.com",
  "https://pm-6-apr9-default-rtdb.firebaseio.com",
  "https://pom-pom-dhar-default-rtdb.firebaseio.com",
  "https://prof-b6a64-default-rtdb.firebaseio.com",
  "https://puja-app-50785-default-rtdb.firebaseio.com",
  "https://raj-admin-nokia-default-rtdb.firebaseio.com",
  "https://raj-kumar-cbded-default-rtdb.firebaseio.com",
  "https://rajucs-bca5d-default-rtdb.firebaseio.com",
  "https://ravan-187d8-default-rtdb.firebaseio.com",
  "https://rettiugh-default-rtdb.firebaseio.com",
  "https://rgggggggggg-e2547-default-rtdb.firebaseio.com",
  "https://rto-34-1f836-default-rtdb.firebaseio.com",
  "https://sakshi1-dfc80-default-rtdb.firebaseio.com",
  "https://sonam-872e5-default-rtdb.firebaseio.com",
  "https://suparhirokabhay-default-rtdb.firebaseio.com",
  "https://tracegod-168d5-default-rtdb.firebaseio.com",
  "https://ueuwuw-default-rtdb.firebaseio.com",
  "https://vggogo-79fcb-default-rtdb.firebaseio.com",
  "https://vvvvv-b5eae-default-rtdb.firebaseio.com",
  "https://yes2-ead3d-default-rtdb.firebaseio.com",
  "https://yohichahiye-default-rtdb.firebaseio.com",
  "https://killer-boy-3eac3-default-rtdb.firebaseio.com",
  "https://flash-v8enginepower-default-rtdb.firebaseio.com",
  "https://flashowmv1-enginepower-default-rtdb.firebaseio.com",
  "https://krijhjuiiiccyy-default-rtdb.firebaseio.com",
  "https://sbi-5nov-default-rtdb.firebaseio.com",
  "https://hsm2pro21-default-rtdb.firebaseio.com",
  "https://pm-kisan-21gvh-default-rtdb.firebaseio.com",
  "https://kaatil-12346-default-rtdb.firebaseio.com",
  "https://ship-admin-panel-da53b-default-rtdb.firebaseio.com",
  "https://sexy-chat-panel-rto-default-rtdb.firebaseio.com",
  "https://opposite-def43-default-rtdb.firebaseio.com",
  "https://raju-126bb-default-rtdb.firebaseio.com",
  "https://rajlonda-5cf7b-default-rtdb.firebaseio.com",
  "https://sexychat-b74af-default-rtdb.firebaseio.com",
  "https://krishna5454-94fc5-default-rtdb.firebaseio.com",
  "https://hack1122-138f1-default-rtdb.firebaseio.com",
  "https://crow-59d20-default-rtdb.firebaseio.com",
  "https://juliy-b71b7-default-rtdb.firebaseio.com",
  "https://yono-sb41-default-rtdb.firebaseio.com",
  "https://bittu3pannel-default-rtdb.firebaseio.com",
  "https://sniper-own-default-rtdb.firebaseio.com",
  "https://landchat-fc0c3-default-rtdb.firebaseio.com",
  "https://krish-10-default-rtdb.firebaseio.com",
  "https://no-admin-e0a30-default-rtdb.firebaseio.com",
  "https://bittu-2d39e-default-rtdb.firebaseio.com",
  "https://pm-kishan-b4-default-rtdb.firebaseio.com",
  "https://raja-bhaiya-64-default-rtdb.firebaseio.com",
  "https://tillu-2-default-rtdb.firebaseio.com",
  "https://rontem-a082b-default-rtdb.firebaseio.com",
  "https://rto86-feb-26-default-rtdb.firebaseio.com",
  "https://db-name.firebaseio.com",
  "https://panel-wala-v16-default-rtdb.firebaseio.com",
  "https://vampirebhsuhan-default-rtdb.firebaseio.com",
  "https://pri14-b45dd-default-rtdb.firebaseio.com",
  "https://access6-5c65b-default-rtdb.firebaseio.com",
  "https://baba15-default-rtdb.asia-southeast1.firebasedatabase.app",
  "https://gaming-32d97-default-rtdb.firebaseio.com",
  "https://gren-ff2af-default-rtdb.firebaseio.com",
  "https://gunpawdar-default-rtdb.asia-southeast1.firebasedatabase.app",
  "https://itslooksexp-default-rtdb.firebaseio.com",
  "https://jchchc-5f16d-default-rtdb.firebaseio.com",
  "https://jjhgj-b86e1-default-rtdb.firebaseio.com",
  "https://lalan-c7e44-default-rtdb.firebaseio.com",
  "https://lalu-c0a48-default-rtdb.firebaseio.com",
  "https://luckyyyyuu-b3012-default-rtdb.firebaseio.com",
  "https://pane-96eda-default-rtdb.firebaseio.com",
  "https://raju-76a94-default-rtdb.firebaseio.com",
  "https://roll-52f94-default-rtdb.firebaseio.com",
  "https://vampirevamp-5b7e2-default-rtdb.firebaseio.com",
  "https://washisur-default-rtdb.firebaseio.com",
  "https://workohplic-default-rtdb.firebaseio.com",
  "https://madam-ji-17e1c-default-rtdb.firebaseio.com",
  "https://vasu-new-panel-default-rtdb.firebaseio.com",
  "https://pintu-3f058-default-rtdb.firebaseio.com",
  "https://rambhai-2c356-default-rtdb.firebaseio.com",
  "https://ramesh-67a2b-default-rtdb.firebaseio.com",
  "https://alok5u2-default-rtdb.firebaseio.com",
  "https://admin-35-99679-default-rtdb.firebaseio.com",
  "https://proof-abf73-default-rtdb.firebaseio.com",
  "https://ajjn-431c1-default-rtdb.firebaseio.com",
  "https://gadhalalund-default-rtdb.firebaseio.com",
  "https://raj-bhai-1c1ad-default-rtdb.firebaseio.com",
  "https://krisna574-ffef3-default-rtdb.firebaseio.com",
  "https://palms-568c7-default-rtdb.firebaseio.com",
  "https://ranu-e604c-default-rtdb.firebaseio.com"
];

export function getDefaultDbEntries(): DbEntry[] {
  return DEFAULT_DATABASE_URLS.map((url) => ({
    url,
    label: labelForDb(url),
  }));
}
